### ISSUE TITLE
An Niklas ( Wind ) fehlerhaftes Mapping an der Main Map

### ISSUE THREAD

**Issue by ErwinOnAir** [ErwinOnAir/pachunt#5]
Es gibt noch lücken in manchen ecken in der Map wo man durchschauen kann bitte fixxen 

![image](https://user-images.githubusercontent.com/106586910/218330711-1fbc4979-57aa-447e-bab2-426289d4b0ac.png)

![image](https://user-images.githubusercontent.com/106586910/218330727-60eb7bd1-bf63-485f-8d39-445963aa72d4.png)

![image](https://user-images.githubusercontent.com/106586910/218330752-cc3ca43e-0090-4fff-8802-e153f3604b62.png)

**Comment by NotWindx** [comment]
Alle Löscher sind gestopft
